CONTRIBUTION-GUIDELINES.md
I've added contribution guidelines; please go over them to see if there's anything I missed or if there are any changes that need to be made.
=> Add contribution guidelines

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature.yml, .github/ISSUE_TEMPLATE/ideas.yml
=> Added Issue Templates

Contributors.md, debug.log
=> [Add profile] -> [Emmanuel Tanimowo]

.github/ISSUE_TEMPLATE/feature.yml, .github/ISSUE_TEMPLATE/ideas.yml
Fixed not working issue templates
=> Fix issue templates

README.md
Add git tutorial link
Add community admin link
None
=> Add important links

Contributors.md
Add my profile to the contributor's list
=> [Add profile] -> [Melford Birakor]

Contributors.md
=> Add Oge Obubu

Contributors.md
=> [Add Profile] -> [Adaeze Ndupu]

Contributors.md
=> [Add profile] -> [Ahmad Adejumo]

Contributors.md
=> add Ajor Moses

Contributors.md
I added myself to the contributors list
=> [Add profile] -> [Mike]

Contributors.md
=> Fix numbering

Contributors.md
=> Add Samson Okunola

Contributors.md
=> [Add-profile] -> [Omololu Jumat]

Contributors.md
Me i don't understand this PR ooh?
Please add my name to the contributor's list
=> [Add profile] -> [Oludamola Onarinde]

Contributors.md
Adds my profile to contributors list
=> [add-tuedon] -> [Tuedon Tuoyo]

Contributors.md
=> [Add profile] -> [David Edu]

Contributors.md
=> Add Olasunkanmi Balogun

Contributors.md
=> Align profile in table

Contributors.md
Added my profile to the contributors list
=> Add Benedict Okafor

Contributors.md
=> [Add profile] -> [Mustapha Olawale]

Contributors.md
Add my profile to the contributor's list
=> [Add profile] -> [Oluwabamise Olatunji]

Contributors.md
Fixed bugs due to improper alignment and duplicates in contributors' list
- Re-arranged the table into rows of 7 columns
- Removed the duplicates in contributors' list
=> this fixes and closes issue #46

Contributors.md
Profile removed after merge added back
=> Add removed profile

Contributors.md
=> [Add Contributor Profile] -> [Franklin Ohaegbulam]

README.md
=> Update contributors screenshot

Contributors.md
`[Add profile] -> [Charles Ejiegbu]`
Add my profile to the contributor's list
=> Add Charles Ejiegbu

Contributors.md
=> fix blurry image

Contributors.md
=> [Add Profile] -> [Okereke Chinweotito]

Contributors.md
Add my profile to the contributors' list.
=> [Add Profile] -> [Williams Samuel]

Contributors.md
=> Dev blade details

CONTRIBUTION-GUIDELINES.md
Update the contribution guidelines
Issue No: #66
=> Update contribution guidelines

Contributors.md
`[Add profile] -> [Ayomide Bamigboye]`
Add my profile to the contributor's list
=> Add Ayomide Bamigboye

Contributors.md
=> [Add profile] -> [Michael Ogunyemi]

Contributors.md
=> [Add profile] -> [Manish Bajagai]

Contributors.md
=> [Add profile] -> [Luke David]

Contributors.md
=> feat: add thuongtruong1009 profile to contributors list

Contributors.md
<h1>What will this PR do?</h1>
<h2>Add my profile</h2>
=> Add Pius Osuji

Contributors.md
Add my profile to the contributors' list.
=> [Add profile] -> [Harsh Kumar Morane]

Contributors.md
I have added my profile to the Contributions.md
=> I have added my profile

Contributors.md
=> [Add profile] -> [Segun Ajibola]

Contributors.md
=> [Add profile] -> [Chandula Janith]

Contributors.md
=> [Add profile] -> [Sagar Malhotra]

Contributors.md
Add my profile to the contributors' list.
=> [Add profile] -> [Enes]

Contributors.md
Add my profile to the list of contributors' list
- How can I know the available community tasks to work on?
=> [Add Profile] -> [Orobola Roland Ogundipe]

Contributors.md
=> Add Ezeugo Felistus Obieze

Contributors.md
<h2>Add Evander </h2>
Add my profile to the contributors' list.
=> Add Evander Inacio

Contributors.md
Add my profile to the contribuitors list
=> [Add profile] ->[Tom]

Contributors.md
- Add my profile to the contributors' list
=> [Add profile] -> [Oluwabusayo Jacobs]

Contributors.md
=> Add Profile -> Adarsh Urmaliya

Contributors.md
=> [Add profile] -> [Ifeanyichukwu Otiwa]

Contributors.md
=> [Add profile] -> [Daniel Adewole]

README.md
=> Change the 'repalce' on line 135 to 'replace'

Contributors.md
=> Add LeaxLang

Contributors.md
add my information to the contribution list
=> `[Add profile] -> [TenTraicion]

Contributors.md
=> Add adivee

Contributors.md
=> Add Tope Akinkuade

Contributors.md
=> [Add profile] -> [Emmanuel Jemeni]

Contributors.md
=> [Add Profile] -> [Abdurrahman Sogbesan]

Contributors.md
Add Benjamin Thorpe to the Contributors.md list
=> Add Benjamin Thorpe

Contributors.md
[Add profile] -> [Jude Leonard]
Adding my profile to contributors' list
=> add Jude Leonard

Contributors.md
**Add Vrinda Daga**
**What does this PR do?**
Add my profile to the Contributor's List.
=> Add [Vrinda] -> [Vrinda Daga]

Contributors.md
=> Added my info

Contributors.md
Add my profile to the contributors list.
=> [Add profile] -> [Chukwu Solomon]

Contributors.md
=> Adding Alexander Clemens

Contributors.md
Add my profile to contributor's list
=> [Add profile] -> [Yann Marc]

Contributors.md
=> Add Umoren Gilbert

Contributors.md
=> [Add profile] -> [Onaivio]

Contributors.md
=> Add Sundaram

Contributors.md
=> Add Rachael Odetayo

Contributors.md
=> Add Muhammad-Arham

Contributors.md
=> Add profile -> Richard Emijere

Contributors.md
=> ## Add Mubashir Iqbal

Contributors.md
`[https://github.com/dekema9924] -> [Daniel Ekema]`
=> daniel ekema

Contributors.md
=> [Add profile] -> [Aravind S Bhat]

Contributors.md
=> adding my name and profile link

Contributors.md
=> [Add profile] -> [Usman Yousaf]
